version: 2.1

executors:
  python-executor:
    docker:
      - image: cimg/python:3.12.4
    working_directory: ~/repo

jobs:
  install-dependencies:
    executor: python-executor
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            pip install --upgrade pip
            pip install -r requirements.txt

  test:
    executor: python-executor
    steps:
      - checkout
      - run:
          name: Install dependencies for testing
          command: |
            pip install --upgrade pip
            pip install -r requirements.txt
      - run:
          name: Run tests
          command: |
            pytest --junitxml=test-results/junit.xml --cov=app --cov-report=xml --cov-report=term
      - store_artifacts:
          path: test-results
          destination: test-results
      - store_artifacts:
          path: coverage.xml
          destination: coverage.xml
      - store_test_results:
          path: test-results

  deploy:
    executor: python-executor
    steps:
      - checkout
      - run:
          name: Deploy application
          command: |
            curl -L https://fly.io/install.sh | sh
            export FLYCTL_INSTALL="/root/.fly"
            export PATH="$FLYCTL_INSTALL/bin:$PATH"
            fly auth token "$FLY_API_TOKEN"
            fly deploy
            fly status

workflows:
  test-and-deploy:
    jobs:
      - install-dependencies
      - test:
          requires:
            - install-dependencies
      - deploy:
          requires:
            - test
